### ISSUE TITLE
Fix the score during the jumpscare

### ISSUE THREAD

**Issue by PontusAhlin** [PontusAhlin/HorrorGame#21]

**Comment by williamfridh** [comment]
I will fix this one by storing the amount of viewers and likes in the storage file (see Storage.cs). The plan is to save the values upon death, and then load then when showing the jumpscare scene.

**Comment by williamfridh** [comment]
Work continued. Need however the MonsterGenerationScript error resolved (see separate issues).

**Comment by williamfridh** [comment]
This is now fixed. Had to add code so that Storage.cs can save the last game's viewer and likes amount, as well as add support in the user interface script to display these values. Lastly, I had to reconnect stuff in the jumpscare scenes as the are disconnected form the player wrapper prefab.
