### ISSUE TITLE
Warning from random monster generation script

### ISSUE THREAD

**Issue by williamfridh** [PontusAhlin/HorrorGame#24]
The script throws warnings (see message below). Sometimes the next monster never spawns.

```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <b11ba2a8fbf24f219f7cc98532a11304>:0)
RandomMonsterGeneration+<GenerateMonster>d__12.MoveNext () (at Assets/Scripts/RandomMapGen/RandomMonsterGeneration.cs:68)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <c5ed782439084ef1bc2ad85eec89e9fe>:0)
```

**Comment by williamfridh** [comment]
Also, why do we have both "Monster Generation.cs" and "RandomMonsterGeneration.cs"? Was the first one part of the old map?

**Comment by williamfridh** [comment]
Noticed it worked when I disabled "Spawn On Of Each"? Maybe look into that.

**Comment by PH77SER** [comment]
fixed, error was that i was spawning stuff from MonsterPrefab 's index but that index starts at 0, and i was counting from 1, so it overflowed
