### ISSUE TITLE
Name and description

### ISSUE THREAD

**Issue by PontusAhlin** [PontusAhlin/HorrorGame#26]
Due Tuesday by 12:00 Points 0 Submitting a text entry box Available 18 Mar at 8:00 - 15 May at 10:00

Scrum Masters, submit the product type, the product name, and the product description.

You can delegate this submission to any team member.

For instructions regarding the submission, please see the page [Expo: Instructions for Teams](https://canvas.kth.se/courses/46149/pages/expo-instructions-for-teams)

**Comment by arnobds** [comment]
Is this enough of for the description? (Copied from the game's website)

In this mobile VR horror game you are a conspiracy theorist live streaming in an insane Asylum. The aim is to capture footage of the paranormal creatures and gain likes on your live stream. But proceed with caution... the longer you stay the more aggressive the creatures become.

**Comment by PontusAhlin** [comment]
Preparation part I: the expo page

"An eye-catching screenshot or image showing the product. The image format must be a Jpeg image (file.jpg), with exactly 250 by 250 pixels. The file size must be smaller than 48 kibibytes (49152 bytes) - preferably much smaller.
    After the image comes the team name (not submitted, supplied by the examiner), such as "Group Alpha's"
    After the team name comes the type of your product, such as "mobile game"
    After the type of product comes the product name in italics. The name is chosen by the team, such as "Rocket Science".
    **Following the team name, type and name of the product comes a dash, then a short description using up to 7 words."**
    
    For instructions see bold text

**Comment by PontusAhlin** [comment]
product type: Mobile game

product name: Ghostleaks

product description: An immersive VR mobile horror game 

People like this?

**Comment by PontusAhlin** [comment]
Went with this:

product type: Mobile game

product name: GhostLeaks

product description: An immersive VR mobile horror game
