### ISSUE TITLE
Product poster

### ISSUE THREAD

**Issue by PontusAhlin** [PontusAhlin/HorrorGame#27]
Due Monday by 12:00 Points 0 Submitting a file upload File types jpg and pdf

Scrum Masters, submit a poster for the product.

You can delegate this submission to any team member.

For instructions regarding the image, please see the page [Expo: Instructions for Teams](https://canvas.kth.se/courses/46149/pages/expo-instructions-for-teams).

**Comment by Ahmad20222** [comment]
Done
