### ISSUE TITLE
Product image or icon

### ISSUE THREAD

**Issue by PontusAhlin** [PontusAhlin/HorrorGame#28]
Due Monday by 12:00 Points 0 Submitting a file upload File types jpg Available 18 Mar at 8:00 - 14 May at 10:00

Scrum Masters, submit an image file showing the product.

You can delegate this submission to any team member.

For instructions regarding the image, please see the page [Expo: Instructions for Teams](https://canvas.kth.se/courses/46149/pages/expo-instructions-for-teams)

**Comment by Ahmad20222** [comment]
Done
