### ISSUE TITLE
monsters spawning generate a warning each time, except the ghost

### ISSUE THREAD

**Issue by PH77SER** [PontusAhlin/HorrorGame#29]
on any monster spawning, the MonsterGenerateViewers.cs script generates a error complaining about viewerRemoveAmount being less than 1, so it'll be set to 1.1. This happens even though the value **IS** 1, and also does not happen when it is **LOWER** than 1.

**Comment by williamfridh** [comment]
Adjusted the unclear log messages. Not it says 1.1 instead of 1 and gives the error even though any of the values are lower than 1.1 as this is the correct limit.
