### ISSUE TITLE
Make it so that the escape scene menu matches the design other other menues

### ISSUE THREAD

**Issue by williamfridh** [PontusAhlin/HorrorGame#30]
When you're at it, maybe change the name of the scene?

- [x] Fix design
- [x] Test the design (for responsiveness)
- [x] Change the name of the scene file
- [x] Change the name of the script file
- [x] Change the name written on the physical token

**Comment by arnobds** [comment]
Done. You can take a look at it.

**Comment by williamfridh** [comment]
Looks good! Great job 💯
