### ISSUE TITLE
Fix/Change the tutorial to show the new features added

### ISSUE THREAD

**Issue by PontusAhlin** [PontusAhlin/HorrorGame#44]
The tutorial is a bit outdated so adding the Joystick movement and Ghost detector (for example) would be good

**Comment by arnobds** [comment]
What text do we want for the Ghost detector? Is there any png image available for the detector?

**Comment by arnobds** [comment]
All done. Only the image of the detector button needs to be added once someone chooses that.

**Comment by williamfridh** [comment]
This is done.
