### ISSUE TITLE
Escape door spawns behind something white (list?)

### ISSUE THREAD

**Issue by williamfridh** [PontusAhlin/HorrorGame#55]
![image](https://github.com/PontusAhlin/HorrorGame/assets/6670273/abc29601-7214-4fd7-8e15-fddd5d935919)

**Comment by williamfridh** [comment]
@PH77SER (Alin?), can you look into this?

**Comment by PH77SER** [comment]
no clue how this happened - this is a 2x2 room and when i generated this in live it looked fine, but i fixed a bug where the exit door would be stuck in the 1x1 corridor wall so, marking this as closed until we find a live example
