### ISSUE TITLE
Add more text messages in the chat and store the messages in a file that we can read from 

### ISSUE THREAD

**Issue by MoritzGruesome** [PontusAhlin/HorrorGame#58]
There are not enough text messages in the live chat. I suggest everyone try and come up with some to add to the different categories.

**Comment by PontusAhlin** [comment]
Also make it possible to store the messages (in a JSON file maybe?)

**Comment by williamfridh** [comment]
The messages are now stored in the file "/Resources/ChatMessages.json". I'll continue with adding messages.

**Comment by williamfridh** [comment]
More messages added.
