### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by MoritzGruesome** [PontusAhlin/HorrorGame#74]
When an achievement is completed, the colour of the box should change to indicate this. 

Maybe change the entire box to green.

**Comment by williamfridh** [comment]
Will look into this!

**Comment by williamfridh** [comment]
Fixed!

**Comment by williamfridh** [comment]
![image](https://github.com/PontusAhlin/HorrorGame/assets/6670273/069efe82-8be8-4141-b5a8-d16f4ec215ef)
